name: yumememo
description: "An aesthetic anime notepad for your thoughts and dreams."
publish_to: 'none'
version: 1.1.0+10

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Packages
  sqflite: ^2.3.3+1
  path: ^1.9.0
  provider: ^6.1.2
  intl: ^0.20.2
  shared_preferences: ^2.2.3 

  # Features & UI
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  sensors_plus: ^6.0.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  in_app_review: ^2.0.9
  flutter_staggered_grid_view: ^0.7.0
  
  # Rich Text Feature
  flutter_quill: ^10.8.0
  shimmer: ^3.0.0

  # Ads and App Info
  google_mobile_ads: ^5.1.0
  package_info_plus: ^8.0.0

  cupertino_icons: ^1.0.8
  video_player: ^2.8.6
  local_auth: ^2.1.6
  file_picker: ^8.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.2.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icon.png
    - assets/videos/
    - assets/videos/night_sky.mp4

  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf

# ✅ Splash Screen Settings (මෙතන මුලට ඉඩ තියන්න එපා)
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
    icon_background_color: "#ffffff"
  android: true
  ios: true